---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - "tests/"
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
    exclude_fingerprints:
    # Allow on() method because this is standard for events
    - 9a2a72fb96d7ecc9c5338bd17c8b82ac
    # Need $event to get the next parameter $ref
    - a7b0748112e24a59b9c29c38ba42b82e
ratings:
  paths:
  - "**.php"
